Namespace: "default"

Service_list:
  - "httpbin-7bb6ccb769-tql6h"

Testcase_list:
#  - method: "GET"
#    url: "/headers"
#    headers:
#      Content-Type: "application/json"
#    body: "{ languages: [ 'Ruby', 'Perl', 'Python', 'c' ] }"
#  - method: "POST"
#    url: "/post"
#    headers:
#      User-Agent: "macos"
#    body:
  - method: "Get"
    url: "/get"
    headers:

Chaos_list:
  - ",delay,100ms"
  - ",loss,50%"